### ISSUE TITLE
Disabling a plugin with non-`active` applications leaves those applications in `teminated lost` state 

### ISSUE THREAD

**Issue by agileshaw** [canonical/snap-openstack#112]
An error occurred during enabling heat plugin in my sunbeam cloud, causing heat related applications to stuck in `waiting` state. So I decide to disable the plugin to remove those applications. The output of from sunbeam shows no error:
```
ubuntu@sunbeam:~$ sunbeam disable heat
OpenStack heat application disabled.
```
but the removal is actually incomplete, leaving those applications in `terminated lost` state:
```
heat-cfn-mysql-router/0      terminated  lost   10.1.232.63         unit stopped by the cloud
heat-cfn/0                   terminated  lost   10.1.232.14         unit stopped by the cloud
heat-mysql-router/0          terminated  lost   10.1.232.62         unit stopped by the cloud
heat/0                       terminated  lost   10.1.232.2          unit stopped by the cloud
```

The problem is like due to provider removing application without `--force` flag, but I think Sunbeam should at least provide an info or warning message when those applications are not fully cleaned.

**Comment by gboutry** [comment]
I thought issues were disabled on this repo.

They must have re-enabled when moving to canonical org. Can you open that issue on bugs.launchpad.net/snap-openstack instead please ?

**Comment by agileshaw** [comment]
Sure no problem.
