### ISSUE TITLE
Openstack 2024.1/edge rev 518 ( From Today ) : No bootstrap juju-controller

### ISSUE THREAD

**Issue by moula** [canonical/snap-openstack#246]
Bonjour, 
Today's version created a bug. No possibility of deploying juju-controllers whereas with yesterday's version everything functions.. 
Thank you so much. 
Moula
![Capture d’écran du 2024-06-05 14-05-05](https://github.com/canonical/snap-openstack/assets/1804815/0856c0f6-d28a-403f-a352-70f5a464a3d4)
![Capture d’écran du 2024-06-04 19-34-12](https://github.com/canonical/snap-openstack/assets/1804815/727dfd37-efb3-46a2-bbba-c5883168c8b6)
![Capture d’écran du 2024-06-04 19-19-36](https://github.com/canonical/snap-openstack/assets/1804815/aba35a6e-39cd-4780-91b3-f05ad61e82a2)

**Comment by gboutry** [comment]
Hello @moula, this will be fixed by https://github.com/canonical/snap-openstack/pull/245

**Comment by gboutry** [comment]
For future reference, the preferred place to open bugs is: https://bugs.launchpad.net/snap-openstack

**Comment by gboutry** [comment]
#245 has been merged
